FROM ubuntu:24.04 as builder
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update && apt -y -qq upgrade
RUN apt -y -qq install \
  build-essential make cmake git pv pkg-config  \
  wget curl xz-utils  \
  openssl ca-certificates

RUN apt -y -qq install \
  libfftw3-bin libfftw3-dev

RUN apt -y -qq install \
  python3 python3-dev python3-setuptools python3-venv pipx

RUN apt -y -qq install \
  qt6-base-dev libqt5core5a \
  && apt clean

RUN git clone --depth 1 --branch v0.3.3 https://github.com/oyvindln/vhs-decode.git && \
  cd vhs-decode

WORKDIR /vhs-decode
# Copy the current requirements.txt into this 'builder' container
COPY requirements.txt ./
RUN pipx install .

RUN mkdir build2 && cd build2 && \
  cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_QWT=OFF -DBUILD_PYTHON=OFF -DBUILD_LDF_READER=OFF && \
  make && make install

# Install tbc-video-export
RUN pipx install https://github.com/JuniorIsAJitterbug/tbc-video-export/releases/download/v0.1.5/tbc_video_export-0.1.5.tar.gz

# Install a ffmpeg static build
RUN wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -O - | \
  tar Jxvf - --wildcards --strip-components=1 ffmpeg-*-amd64-static/ffmpeg && \
  cp ffmpeg /usr/local/bin/

# todo: copy flac v1.5.0 into container

# FROM ubuntu:24.04
# ARG DEBIAN_FRONTEND=noninteractive

# RUN apt-get -qq update && \
#   apt -y -qq upgrade && \
#   apt -y -qq install --autoremove libqt6core6 libfftw3-3 python3 && \
#   apt-get clean && \
#   rm -rf /var/lib/apt/lists/*
# # Copy binaries and python bits from build image
# COPY --from=builder /usr/local/bin/* /usr/local/bin/
# COPY --from=builder /root/.local /root/.local/
ENV PATH=/root/.local/bin:$PATH
CMD ["/bin/bash"]
